### Python is convenient, but it can also be slow. However, it does allow you to access libraries that execute faster code written in languages like C. NumPy is one such library: it provides fast alternatives to math operations in Python and is designed to work efficiently with groups of numbers - like matrices.

### The most common way to work with numbers in NumPy is through ndarray objects. They are similar to Python lists, but can have any number of dimensions. Also, ndarray supports fast math operations, which is just what we want.

### Since it can store any number of dimensions, you can use ndarrays to represent any of the data types we covered before: scalars, vectors, matrices, or tensors. (Tensors are any n-dimensional data structures above 2 dimensions).

In [3]:
import numpy as np

#### If you want to create a NumPy array that holds a scalar, you do so by passing the value to NumPy's array function, like so:

In [4]:
s = np.array(5)

In [5]:
s

array(5)

#### You can still perform math between ndarrays, NumPy scalars, and normal Python scalars, though.

#### Even though scalars are inside arrays, you still use them like a normal scalar. So you could type

In [6]:
x = s + 3

In [7]:
x

8

#### If you were to check the type of x, you'd find it is probably numpy.int64, because its working with NumPy types, not Python types.

In [8]:
type(x)

numpy.int32

#### By the way, even scalar types support most of the array functions. so you can call x.shape and it would return () because it has zero dimensions, even though it is not an array. If you tried that with a normal Python scalar, you'd get an error.

In [10]:
x.shape

()

In [11]:
# Lets try calling shape on a Python scalar
y = 10

In [12]:
y.shape

AttributeError: 'int' object has no attribute 'shape'

### To create a vector, you'd pass a Python list to the array function, like this:

In [14]:
# Create a list
my_list = [534, 5468, 6546, 542, 9856, 4125]

### Create a ndarray from the list

In [15]:
nparray = np.array(my_list)

### What are the dimensions of the array?

In [20]:
# If you check a vector's shape attribute, it will return a single number representing the vector's one-dimensional length.
nparray.shape

(6,)

#### You can see that the shape is a tuple with the sizes of each of the ndarray's dimensions. For scalars it was just an empty tuple, but vectors have one dimension, so the tuple includes a number and a comma. (Python doesn’t understand (3) as a tuple with one item, so it requires the comma).

In [21]:
nparray.ndim

1

### Create Multidimensional Arrays 
#### You create matrices using NumPy's array function, just you did for vectors. However, instead of just passing in a list, you need to supply a list of lists, where each list represents a row. 

In [17]:
my_list1 = [4277, 24368, 2546, 1542, 576, 285]

### Create a ndarray from a nested list

In [18]:
nparray = np.array([my_list, my_list1])

In [19]:
nparray

array([[  534,  5468,  6546,   542,  9856,  4125],
       [ 4277, 24368,  2546,  1542,   576,   285]])

In [20]:
nparray.shape

(2, 6)

### Generating Random Numbers With Numpy

### Generate A Random Number From The Normal Distribution

In [21]:
np.random.normal()

-1.589918702493253

### Generate Multiple Random Numbers From The Normal Distribution

In [22]:
np.random.normal(size=4)

array([ 0.79291036,  0.4688816 ,  0.72780739,  0.11383578])

### Generate Four Random Numbers From The Uniform Distribution

In [23]:
np.random.uniform(size=4)

array([ 0.76042978,  0.25426759,  0.01660121,  0.80156425])

### Generate Four Random Integers Between 1 and 100

In [24]:
np.random.randint(low=1, high=100, size=4)

array([24,  4, 16, 75])

### Create an Array of Zeroes and Range Generator

In [27]:
npzeroes = np.zeros(6)
npzeroes

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [30]:
# Create a range from 0 to 100
zero_to_99 = np.arange(0, 100)
zero_to_99

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Create 100 ticks between 0 and 1

In [31]:
zero_to_1 = np.linspace(0, 1, 100)
zero_to_1

array([ 0.        ,  0.01010101,  0.02020202,  0.03030303,  0.04040404,
        0.05050505,  0.06060606,  0.07070707,  0.08080808,  0.09090909,
        0.1010101 ,  0.11111111,  0.12121212,  0.13131313,  0.14141414,
        0.15151515,  0.16161616,  0.17171717,  0.18181818,  0.19191919,
        0.2020202 ,  0.21212121,  0.22222222,  0.23232323,  0.24242424,
        0.25252525,  0.26262626,  0.27272727,  0.28282828,  0.29292929,
        0.3030303 ,  0.31313131,  0.32323232,  0.33333333,  0.34343434,
        0.35353535,  0.36363636,  0.37373737,  0.38383838,  0.39393939,
        0.4040404 ,  0.41414141,  0.42424242,  0.43434343,  0.44444444,
        0.45454545,  0.46464646,  0.47474747,  0.48484848,  0.49494949,
        0.50505051,  0.51515152,  0.52525253,  0.53535354,  0.54545455,
        0.55555556,  0.56565657,  0.57575758,  0.58585859,  0.5959596 ,
        0.60606061,  0.61616162,  0.62626263,  0.63636364,  0.64646465,
        0.65656566,  0.66666667,  0.67676768,  0.68686869,  0.69

### Indexing and Slicing Numpy Arrays

In [32]:
# Create a 2x2 array
battle_deaths = [[344, 2345], [253, 4345]]
deaths = np.array(battle_deaths)
deaths

array([[ 344, 2345],
       [ 253, 4345]])

In [33]:
# Select the top row, second item
deaths[0, 1]

2345

In [37]:
# Select the second column
deaths[:, 1]

array([2345, 4345])

In [48]:
# Select the second row
deaths[1, :]

array([ 253, 4345])

### Applying Conditions Using np.where() 

In [49]:
few_deaths = np.where(deaths[1,:] > 500)

In [50]:
few_deaths

(array([1], dtype=int64),)

#### Lets try that on a single-dimension array

In [54]:
death_count = [2131,534,3453,57,12432,4542,1241,5457]

In [55]:
death_count = np.array(death_count)

In [56]:
few_deaths = np.where(death_count<3000)

In [57]:
few_deaths

(array([0, 1, 3, 6], dtype=int64),)

### Find out Mean

In [58]:
death_count.mean()

3730.875

### Find out Sum

In [59]:
death_count.sum()

29847

### Min and Max

In [60]:
death_count.min()

57

In [62]:
death_count.max()

12432

### More Slicing and Indexing

In [70]:
# Divide the array of battle deaths into start, middle, and end of the war
warStart = death_count[0:2]; print('Death from battles at the start of war:', warStart)
warMiddle = death_count[2:4]; print('Death from battles at the middle of war:', warMiddle)
warEnd = death_count[4:7]; print('Death from battles at the end of war:', warEnd)

Death from battles at the start of war: [11101   534]
Death from battles at the middle of war: [3453   57]
Death from battles at the end of war: [12432  4542  1241]


## Broadcasting

### Change Value using Array Index

In [71]:
# Change the battle death numbers from the first battle
warStart[0] = 11101

In [72]:
warStart

array([11101,   534])

In [73]:
# View that change reflected in (i.e. "broadcasted to) the original death_count array
death_count

array([11101,   534,  3453,    57, 12432,  4542,  1241,  5457])

### Create a multidimensional array which behaves like a dataframe or matrix (i.e. columns and rows)

#### Create an array of fraternity brother information

In [ ]:
brother_names = ['Glory', 'Mark', 'Lauren', 'Jelena', 'Kristina']
age = [20, 21, 21, 20, 21]
major = ["Marketing", "MIS", "Accounting", "Economics", "Finance"]
year = [4, 3, 4, 3, 4]

regiments = np.array([regimentNames, regimentNumber, regimentSize, regimentCommander])
regiments

### A little Introduction to Tensors

Like, we discussed before, any data matrix that has more than two dimension is a Tensor.

In [24]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [25]:
t.shape

(3, 3, 2, 1)

#### How do we access the elements?? Similar way of indexing.

In [26]:
t[2][1][1][0]

16

### Changing Shapes
Sometimes you'll need to change the shape of your data without actually changing its contents. For example, you may have a vector, which is one-dimensional, but need a matrix, which is two-dimensional. There are two ways you can do that.

Let's say you have the following vector:

In [32]:
v = np.array([1,2,3,4])

In [33]:
v

array([1, 2, 3, 4])

#### Calling v.shape would return (4,). But what if you want a 1x4 matrix? You can accomplish that with the reshape function, like so:

In [28]:
x = v.reshape(1,4)

In [29]:
x.shape

(1, 4)

#### If you wanted a 4x1 matrix, you could do this:

In [30]:
x = v.reshape(4,1)

In [31]:
x

array([[1],
       [2],
       [3],
       [4]])

### One more thing about reshaping NumPy arrays: if you see code from experienced NumPy users, you will often see them use a special slicing syntax instead of calling reshape. Using this syntax, the previous two examples would look like this:

In [34]:
x = v[None, :]

In [35]:
x

array([[1, 2, 3, 4]])

In [36]:
x = v[:, None]

In [37]:
x

array([[1],
       [2],
       [3],
       [4]])

#### Those lines create a slice that looks at all of the items of v but asks NumPy to add a new dimension of size 1 for the associated axis. It's a common technique so it's good to be aware of it.

### More Examples on Reshaping

In [38]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
np.reshape(a, (2, 3)) # C-like index ordering

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
np.reshape(np.ravel(a), (2, 3)) # equivalent to C ravel then C reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
np.reshape(a, (2, 3), order='F') # Fortran-like index ordering

array([[0, 4, 3],
       [2, 1, 5]])

In [42]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [48]:
np.reshape(a, 6) # Collapse it into a one-dimensional array.

array([1, 2, 3, 4, 5, 6])

In [49]:
a = np.array([[1,2,3], [4,5,6]])

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [67]:
c = np.reshape(a, (1, -3))

In [68]:
c

array([[1, 2, 3, 4, 5, 6]])

In [69]:
c.shape

(1, 6)

In [59]:
np.reshape(a, (2, -3))

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.reshape(a, (3, -3))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
np.reshape(a, (3, -1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
np.reshape(a, (3, -2))

array([[1, 2],
       [3, 4],
       [5, 6]])

## Math Operations in Numpy
NumPy actually has functions for things like adding, multiplying, etc. But it also supports using the standard math operators. So the following two lines are equivalent:

#### We will usually use the operators instead of the functions because they are more convenient to type and easier to read, but it's really just personal preference.

#### One more example of operating with scalars and ndarrays. Let's say you have a matrix m and you want to reuse it, but first you need to set all its values to zero. Easy, just multiply by zero and assign the result back to the matrix, like this:

In [70]:
m = a

In [71]:
m.shape

(2, 3)

In [73]:
m *= 0
# now every element in m is zero, no matter how many dimensions it has

In [74]:
m

array([[0, 0, 0],
       [0, 0, 0]])