In [1]:
import numpy as np

In [2]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,6,7]]])

In [3]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 6, 7]]])

In [4]:
arr3d.T

array([[[1, 7],
        [4, 3]],

       [[2, 8],
        [5, 6]],

       [[3, 9],
        [6, 7]]])

In [5]:
arr = np.random.randn(6,4)

In [6]:
arr

array([[ 0.03029279,  0.16125647, -1.23249297,  0.89099828],
       [-0.88763903, -0.99219349, -0.4685721 ,  0.36788272],
       [ 0.17662961,  0.71564241, -0.75947266, -0.40628662],
       [ 0.452825  ,  1.84399408,  0.22638614, -0.36006915],
       [-0.17278756,  1.91193124,  0.29162021, -1.05091497],
       [ 0.05770302, -1.44324823,  0.5264666 , -1.80831329]])

In [7]:
np.dot(arr.T,arr)

array([[  1.05825437,   1.4333671 ,   0.32694554,  -0.4571269 ],
       [  1.4333671 ,  10.66135627,  -0.06215361,  -0.57548512],
       [  0.32694554,  -0.06215361,   2.72885757,  -2.30196438],
       [ -0.4571269 ,  -0.57548512,  -2.30196438,   5.59835347]])

In [8]:
### For higher dimensional arrays, transpose will accept a tupe of axis numbers to permute teh axes.

arr1 = np.arange(16).reshape((2,2,4))

In [9]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
arr1.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [13]:
### We can also define how the transpose ought to be done

In [14]:
arr1.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [15]:
### Simple transpose with .T is just a special case of swapping axes.

### ndarray has the method swapaxes which takes a pair of axis numbers

arr1.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [17]:
arr1.swapaxes(0,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [ ]:
### swapaxes returns only a view and doesn't create a copy